[tool.poetry]
name = "model"
version = "0.1.0"
description = ""
authors = ["jhands0 <jamie_hands@yahoo.co.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
